<?php

namespace OC\PlatformBundle\Repository;

use OC\UserBundle\Entity\User;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getCategoriesByUser(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.user = :user')
                     ->setParameter('user', $user);
        return $queryBuilder->getQuery()->getResult();
    }
    
    public function getLikeQueryBuilder(User $user)
    {
        $queryBuilder = $this->createQueryBuilder('c');
        $queryBuilder->where('c.user = :user')
        ->setParameter('user', $user);
        return $queryBuilder;
    }
}
