<?php

namespace OC\PlatformBundle\Repository;

/**
 * SoldeInitialRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SoldeInitialRepository extends \Doctrine\ORM\EntityRepository
{
}
